site_name: FPS Leader Communications
site_url: https://fps-leader.com
theme: cinder
pages:
    - This Week @ FPS: index.md
    - Fusion Weekend: fusion.md
    - Movement Conference: movement.md
