site_name: FPS-Leader.com
site_url: https://fps-leader.com
pages:
    - This Wednesday 2/21: index.md
    - Fusion 2018: fusion.md
    - Movement 2018: movement.md
    - Groups: groups.md
theme: readthedocs
